spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/stockSolido}
server.servlet.session.timeout=30m
 
app.admin.username=${APP_ADMIN_USERNAME:Admin_PBPF}
app.admin.password=${APP_ADMIN_PASSWORD:LuisLeoNazSamuel}
 
app.powerbi.username=${APP_POWERBI_USERNAME:powerbi}
app.powerbi.password=${APP_POWERBI_PASSWORD:powerbi123}