spring.data.mongodb.uri=mongodb+srv://Admin_PBPF:LuisLeoNazSamuel@cluster0.wnjmtv8.mongodb.net/stocksolido?retryWrites=true&w=majority

app.admin.username=Admin_PBPF
app.admin.password=LuisLeoNazSamuel

app.powerbi.username=powerbi
app.powerbi.password=powerbi123